apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pod-coordinator.fullname" . }}
  labels:
    {{- include "pod-coordinator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pod-coordinator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pod-coordinator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pod-coordinator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WEBHOOK_PORT
              value: {{ .Values.admissionWebhooks.service.port | quote }}
            - name: SECRET_NAME
              value: {{ include "pod-coordinator.fullname" . | quote }}
            - name: SERVICE_NAME
              value: {{ include "pod-coordinator.fullname" . | quote }}
            - name: MUTATING_WEBHOOK_CONFIGURATION_NAME
              value: {{ include "pod-coordinator.fullname" . | quote }}
            - name: VALIDATING_WEBHOOK_CONFIGURATION_NAME
              value: {{ include "pod-coordinator.fullname" . | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WEBHOOK_CERT_DIR
              value: {{ .Values.admissionWebhooks.certificate.mountPath | quote }}
          volumeMounts:
            - mountPath: {{ .Values.admissionWebhooks.certificate.mountPath }}
              name: cert
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ template "pod-coordinator.fullname" . }}-admission
