apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pool-coordinator.fullname" . }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "pool-coordinator.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /pool-coordinator-webhook-mutate
  failurePolicy: Fail
  name: mpoolcoordinator.kb.io
  rules:
  - apiGroups:
    - pool-coordinator.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None

