apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-coordinator-webhook
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-coordinator-webhook-role
rules:
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
    - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-coordinator-webhook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-coordinator-webhook-role
subjects:
- kind: ServiceAccount
  name: pod-coordinator-webhook
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: pod-coordinator-webhook
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: pod-coordinator-webhook
---
apiVersion: v1
kind: Secret
metadata:
  name: pod-coordinator-webhook-certs
  namespace: kube-system
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: pod-coordinator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: pod-coordinator-webhook-service
      namespace: kube-system
      path: /pod-coordinator-webhook-validate
  failurePolicy: Fail
  rules:
  - apiGroups:
    - pod-coordinator.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - pods
  sideEffects: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pod-coordinator-webhook
  name: pod-coordinator-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-coordinator-webhook
  template:
    metadata:
      labels:
        app: pod-coordinator-webhook
    spec:
      containers:
        - image: aibox03.bj.intel.com:5000/pod-coordinator-webhook:latest
          imagePullPolicy: Always
          name: pod-coordinator-webhook
          env:
            - name: WEBHOOK_NAMESPACE
              value: "kube-system"
            - name: WEBHOOK_SERVICE
              value: "pod-coordinator-webhook"
            - name: WEBHOOK_CONFIGURATION
              value: "pod-coordinator-webhook-configuration"
            - name: VALIDATE_WEBHOOK_NAME
              value: "pod-coordinator-validating.openyurt.io"
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
      serviceAccountName: pod-coordinator-webhook
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
