apiVersion: v1
kind: ServiceAccount
metadata:
  name: ycm-webhook
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ycm-webhook-role
rules:
  - apiGroups:
      - policy/v1beta1
    resources:
      - pods/eviction
    verbs:
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ycm-webhook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ycm-webhook-role
subjects:
- kind: ServiceAccount
  name: ycm-webhook
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: ycm-webhook
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ycm-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ycm-webhook
  name: ycm-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ycm-webhook
  template:
    metadata:
      labels:
        app: ycm-webhook
    spec:
      containers:
        - image: aibox03.bj.intel.com:5000/ycm-webhook:latest
          imagePullPolicy: IfNotPresent
          name: simple-webhook
          env:
            - name: TLS
              value: "true"
          volumeMounts:
            - name: tls
              mountPath: "/etc/ycm-webhook/tls"
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: tls
          secret:
            secretName: ycm-webhook-tls
      serviceAccountName: ycm-webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: ycm-webhook-configuration
webhooks:
  - name: ycm-eviction-validating.openyurt.io
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups:
          - policy
        apiVersions:
          - v1beta1
        operations:
          - CREATE
        resources:
          - pods/eviction
        scope: "*"
    clientConfig:
      service:
        namespace: kube-system
        name: ycm-webhook
        path: /ycm-validate-evictions
        port: 443
      caBundle: Cg==
    admissionReviewVersions:
      - v1
    sideEffects: None
    timeoutSeconds: 2
  - name: ycm-pod-validating.openyurt.io
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - pods
    clientConfig:
      service:
        namespace: kube-system
        name: ycm-webhook
        path: /ycm-validate-pods
        port: 443
      caBundle: Cg==
    admissionReviewVersions:
      - v1
    sideEffects: None
    timeoutSeconds: 2
