{{- if and .Values.admissionWebhooks.enabled .Values.admissionWebhooks.patch.enabled (not .Values.admissionWebhooks.certManager.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ template "pool-coordinator.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "pool-coordinator.name" . }}-admission
    {{- include "pool-coordinator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "pool-coordinator.fullname" . }}-admission
subjects:
  - kind: ServiceAccount
    name: {{ template "pool-coordinator.fullname" . }}-admission
    namespace: {{ .Release.Namespace }}
{{- end }}
